In [6]:
# conda install -c anaconda py-xgboost 

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /Users/sa/opt/anaconda3

  added / updated specs:
    - py-xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _py-xgboost-mutex-2.0      |            cpu_0           8 KB  anaconda
    ca-certificates-2020.1.1   |                0         132 KB  anaconda
    certifi-2019.11.28         |           py37_0         156 KB  anaconda
    conda-4.8.3                |           py37_0         3.0 MB  anaconda
    libxgboost-0.90            |       h0a44026_1         2.4 MB  anaconda
    openssl-1.1.1d             |       h1de35cc_4         3.4 MB  anaconda
    py-xgboost-0.90            |   py37h0a44026_1          77 KB  anaconda
    ------

In [85]:
conda update -n base -c defaults conda

Solving environment: done

## Package Plan ##

  environment location: /Users/sa/opt/anaconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _py-xgboost-mutex-2.0      |            cpu_0           8 KB
    ca-certificates-2020.1.1   |                0         125 KB
    certifi-2019.11.28         |           py37_0         153 KB
    conda-4.8.3                |           py37_0         2.8 MB
    openssl-1.1.1d             |       h1de35cc_4         2.2 MB
    ------------------------------------------------------------
                                           Total:         5.3 MB

The following packages will be REMOVED:

  python_abi-3.7-1_cp37m

The following packages will be SUPERSEDED by a higher-priority channel:

  _py-xgboost-mutex                                anaconda --> pkgs/main
  ca-certificates                                  

In [84]:
conda install -c conda-forge xgboost 

Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Solving environment: - 
  - anaconda/osx-64::ca-certificates-2020.1.1-0, anaconda/osx-64::openssl-1.1.1d-h1de35cc_4
  - anaconda/osx-64::openssl-1.1.1d-h1de35cc_4, defaults/osx-64::ca-certificates-2020.1.1-0
  - anaconda/osx-64::ca-certificates-2020.1.1-0, defaults/osx-64::openssl-1.1.1d-h1de35cc_4
  - defaults/osx-64::ca-certificates-2020.1.1-0, defaults/osx-64::openssl-1.1.1d-h1de35ccdone

## Package Plan ##

  environment location: /Users/sa/opt/anaconda3

  added / updated specs:
    - xgboost


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py37_0         148 KB  conda-forge
    conda-4.8.3                |   py37hc8dfbb8_1         3.0 MB  conda-forge
  

In [39]:
# pip install gensim

     |████████████████████████████████| 23.7 MB 12.9 MB/s eta 0:00:01
     |████████████████████████████████| 103 kB 6.2 MB/s eta 0:00:01
     |████████████████████████████████| 128 kB 11.6 MB/s eta 0:00:01
  Using cached jmespath-0.9.5-py2.py3-none-any.whl (24 kB)
     |████████████████████████████████| 6.1 MB 1.4 MB/s eta 0:00:01
  Using cached s3transfer-0.3.3-py2.py3-none-any.whl (69 kB)
  Using cached docutils-0.15.2-py3-none-any.whl (547 kB)
  Created wheel for smart-open: filename=smart_open-2.0.0-py3-none-any.whl size=101341 sha256=a678d64f8d39a5bc4cf3eb20ed5183aa0dc233b2de8a3818c368bb5ebc1499f5
  Stored in directory: /Users/sa/Library/Caches/pip/wheels/bb/1c/9c/412ec03f6d5ac7d41f4b965bde3fc0d1bd201da5ba3e2636de
Successfully built smart-open
  Attempting uninstall: docutils
    Found existing installation: docutils 0.16
    Uninstalling docutils-0.16:
      Successfully uninstalled docutils-0.16
Note: you may need to restart the kernel to use updated packages.


In [127]:
# Data
import numpy as np
import pandas as pd

# NLP
import re
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import gensim
from gensim import utils
import gensim.parsing.preprocessing as gsp
from wordcloud import WordCloud

# Modeling
from sklearn.naive_bayes import MultinomialNB
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, f1_score, classification_report, confusion_matrix
from sklearn.utils import shuffle
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

# plot
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

ps = PorterStemmer()
stopwords_english = set(stopwords.words('english'))

# 1. Import Data

## 1.1 Load Data

In [128]:
trump = pd.read_csv('/Users/sa/Desktop/NLP_The-2020-Presidential-Race-master-2/Data/All_Candidates/Donald_Trump.csv')

## 1.2 Annotate Data

In [129]:
trump['text'][355]

'Hide highlightingFull TextTranslateUndo Translation FromToTranslateTranslation in progress... \n\n[[missing key: loadingAnimation]]The full text may take 40-120 seconds to translate; larger documents may take longer.\n\nCancel\nOverlayEndTurn on search term navigationTurn on search term navigation\n| Jump to first hit\nPresident Trump delivered a straightforward message to the millions of football fans watching the Super Bowl on Sunday: "The best is yet to come," he declared in a campaign ad that ran after the game.\nBut exactly what comes next for Mr. Trump if he wins a second term is still under discussion at the White House, even as the president plans to continue crisscrossing the nation campaigning—now\nwith a Senate acquittal\n, rising approval ratings and increased confidence in his re-election prospects.\nSenior aides—led by Chris Liddell, the White House\'s deputy chief of staff for policy coordination—have been meeting since late last year to chart an agenda for the se

In [130]:
trump['title'][355]


"Trump's Second-Term Agenda Still on the Drawing Board; The president rarely discusses what he would do if he wins another term, but his advisers have begun to sketch out ideas"

In [131]:
# hand annotation indicies
# positive = [320, 321, 323, 324, 326, 344, 346, 348, 349, 355]

# negative = [1, 2, 3, 6, 7, 9, 10, 11, 12, 17, 18, 100, 332]

# neutral = [0, 4, 5, 8, 13, 14, 15, 16, 19, 300, 310, 325, 328, 341, 352]

In [132]:
positive_trump = [447,408, 395, 389, 377, 374, 372, 320, 321, 323, 324, 326, 344, 346, 348, 349, 355, 106, 338, 419]

negative_trump = [448, 396, 394, 1, 2, 3, 6, 7, 9, 10, 11, 12, 17, 18, 100, 332, 120, 29, 30, 36, 48]

neutral_trump = [443, 432, 418, 398, 373, 365, 364, 4, 5, 8, 14, 16, 19, 253, 300, 310, 325, 328, 341, 352]

In [133]:
# create new col for sentiment

trump['sentiment'] = ""

In [134]:
# populate rows in new col with corresponding sentiment

for i in trump.index:
    for j in positive:
        if i == j:
            trump.at[i,'sentiment'] = 'pos'
            
for i in trump.index:
    for j in neutral:
        if i == j:
            trump.at[i,'sentiment'] = 'neutral'
            
for i in trump.index:
    for j in negative:
        if i == j:
            trump.at[i,'sentiment'] = 'neg'

In [135]:
# select text and news company names
trump_sentiment = trump[['text', 'sentiment']]

In [136]:
# define a function to create corpus for each sentiment

def create_corpus(trump_sentiment, sentiment_name):
    
    df1 = trump_sentiment.loc[trump_sentiment['sentiment'] == sentiment_name]
    #df2 = Sanders_news.loc[Sanders_news['media'] == media_name]
    #df3 = Trump_news.loc[Trump_news['media'] == media_name]
    #frames = [df1, df2, df3]
    #df = pd.concat(frames, ignore_index = True)
    
    return df1

In [137]:
# create small corpus for each sentiment
POS = create_corpus(trump_sentiment, sentiment_name = 'pos')
NEG = create_corpus(trump_sentiment, sentiment_name = 'neg')
NEUTRAL = create_corpus(trump_sentiment, sentiment_name = 'neutral')

In [138]:
corpus_All_sentiment = pd.concat([POS, NEG, NEUTRAL], axis = 0, ignore_index = True)
corpus_All_sentiment.head(5)

text sentiment
0  Hide highlightingFull TextTranslateUndo Transl...       pos
1  Hide highlightingFull TextTranslateUndo Transl...       pos
2  Hide highlightingFull TextTranslateUndo Transl...       pos
3  Hide highlightingFull TextTranslateUndo Transl...       pos
4  Hide highlightingFull TextTranslateUndo Transl...       pos

In [139]:
corpus_All_sentiment.text[0]

'Hide highlightingFull TextTranslateUndo Translation FromToTranslateTranslation in progress... \n\n[[missing key: loadingAnimation]]The full text may take 40-120 seconds to translate; larger documents may take longer.\n\nCancel\nOverlayEndTurn on search term navigationTurn on search term navigation\n| Jump to first hit\nOXON HILL, Md.—The impeachment of President Trump motivated her to fly up from Texas, but after a half day at the Conservative Political Action Conference, Cathie Broten was convinced a more sinister force is in play.\n"It\'s like Custer\'s Last Stand: the Republicans vs. the socialists," said Ms. Broten, 70 years old, wearing a pin reading, "Kiss me, I\'m a capitalist."\n"We need to stand up and fight," she said Thursday. "Somebody\'s got to pay for the free TV, the free college. It\'s time to draw the line."\nWhile Mr. Trump is certain to be greeted by rapturous applause when he addresses CPAC on Saturday afternoon, another name has featured as prominently as the pr

# 2. Data Preprocessing

In [140]:
stop_words = list(set(stopwords.words('english')))
more_words = ['Mr.', '--', 'highlightingFull', '-', '_', 'In', "Ms.", 'but', 'First', 'one', 'keep', "The", 'said',
              'TextTranslateUndo','Translation',  'FromToTranslateTranslation',  'progress...',  '[[missing',  'key:',  
              'loadingAnimation]]The',  'full',  'text',  'may',  'take',  '40-120',  'seconds',  'translate;',  'larger',  
              'documents',  'may',  'take',  'longer.',  'Cancel',  'OverlayEndTurn',  'search',  'term',  'navigationTurn',  
              'search',  'term',  'navigation',  '|',  'Jump',  'first',  'hitWith',  "president's", 'And', 'could', 'going',
              'get', 'FOR', 'would', 'president', 'But', 'AND', 'I', "ANY", 'AS', 'OR', 'He', "Trump's", 'also', 'use', 'make',
              '"AS', 'hide', 'two', 'want', 'way', 'even', 'last', 'said', 'said,', 'said.', 'A', 'made', 'time', 'using', 
              'Trump,', 'BY', 'ProQuest', 'licensors', 'translations', 'NEW', 'YORK', 'Times', 'New', 'York', 'think', 'This',
              'including', 'told', "The'", "Hide'", 'Mr', 'translation', "I'", "but'", "s'", "In'", "It'", "much'", "He'",
              'functionality', "'|", '*', "'I", '.', 'Washinton', 'Post', 'washpost', 'com', 'wsj', '/"', 'mr', 'm', 'a', 'mr.',
              'ms.', "new", "a", "york", "a", "proquest", "Hide", "highlighting", "Full", "Text", "Translate", "Undo", 
              "Translation", "From", "To", "TranslateTranslation", "in", "progress", "[", "missing", "key", ":",
              "loadingAnimation", "]", "may", "take", "seconds", "translate", "larger", "documents", "longer", "Cancel",
              "OverlayEndTurn", "Turn", "on", "search", "term", "navigation", "navigation", "Jump", "to", "first", "hit",
              "(", "PHOTOGRAPHS", "BY" "ASSOCIATED", "PRESS", "Word", "count", "Show", "less", "You", "have", "requested",
               "on-the-fly", "machine", "translation", "selected", "content", "from", "our", "databases", "This", 
              "functionality", "provided", "solely", "your", "convenience", "no", "way", "intended", "replace", "human",
              "Show", "disclaimer", "Neither", "ProQuest", "nor", "its", "licensors", "make", "any", "representations",
              "warranties", "with", "respect", "translations", "are", "automatically", "generated", "retained", "systems"
              "PROQUEST", "LICENSORS", "SPECIFICALLY", "DISCLAIM", "ANY", "ALL", "EXPRESS", "OR", "IMPLIED", "WARRANTIES",
              "INCLUDING", "WITHOUT", "LIMITATION", "AVAILABILITY", "ACCURACY", "TIMELINESS", "COMPLETENESS", "NON-INFRINGMENT", 
              "MERCHANTABILITY", "FITNESS", "PARTICULAR", "PURPOSE", "use", "restrictions", "contained", "Electronic",
              "Products", "License", "Agreement", "agree", "forgo", "claims", "against", "ProQuest", "output", "derived",
              "there", "from", "disclaimer", "Longer", "documents", "while", "Rather", "than", "keep", "you", "waiting", 
              "we", "have", "only", "translated", "paragraphs", "Click", "button", "below", "rest", "document", "Translate",
              "AllCopyright", "Company", "fly", 'systems', 'NON', 'part', 'lessYou', 'week', 'many', 'say', 'year', 'day',
              'INFRINGMENT', 'AVAILABLE', 'disclaimerNeither', 'back', 'whether', 'much', 'still', 'since', 'then', 'according',
              'come', 'thing', 'know', 'see', "saying", 'still', 'subject', 'PROQUEST', 'highlightingfull', 'texttranslateundo',
              'fromtotranslatetranslation', 'loadinganimationthe', 'cancel', 'overlayendturn', 'navigationturn', 'jump', 
              'hitwith', 'ad', 'like', 'highlightingFull', "TextTranslateUndo", 'Translation','FromToTranslateTranslation'
              'progress', 'missing', 'key', 'loadingAnimation', 'seconds', 'navigationTurn', 'search', 'term'
              ]
more_stop_words = stop_words + more_words

In [141]:
def Data_Preprocessing(corpus):
    # convert string to list i.e. ['hide', 'highlightingfull', '[[missing']
    corpus['text'] = corpus['text'].str.split()
    
    corpus['text'] = corpus['text'].apply(lambda x: [item for item in x if item not in more_stop_words])
    
    # lower case each item in the list, and remove non-alphabetic characters i.e. ['hide', 'highlightingfull', 'missing']
    corpus['text'] = corpus['text'].apply(lambda x: [re.sub(r'[^a-zA-Z]', "",y.lower()) for y in x])

    # join the item in the list back to a string and replace keywords containing the target names
#     keywords = ['new york times', 'the new york times', 'international new york times'
#                 "the washington post", "WP Company LLC", "washpostcom",
#                 'wall street journal', 'thomaswsjcom', 'Dow Jones Company Inc.']
    corpus['text'] = corpus['text'].apply(lambda x: [' '.join(x)])

    # stem each word in the text
    corpus['text'] = corpus['text'].apply(lambda x: str(x[0]))
    corpus['text'] = corpus['text'].str.split()
    corpus['text'] = corpus['text'].apply(lambda x: [ps.stem(y) for y in x])

    # join the item in the list back to a string
    corpus['text'] = corpus['text'].apply(lambda x: [' '.join(x)])

    # convert list to a string
    corpus['text'] = corpus['text'].apply(lambda x: str(x[0]))

    print(type(corpus.iloc[0]['text']))
    
    return corpus

In [142]:
processed_sentiment_corpus = Data_Preprocessing(corpus_All_sentiment)
processed_sentiment_corpus[0:5]

<class 'str'>


text sentiment
0  oxon hill mdthe impeach presid trump motiv tex...       pos
1  washingtonin three year offic presid trump ove...       pos
2  rancho mirag calif republican senat face tight...       pos
3  washingtonpresid trump major nation audienc pa...       pos
4  davo switzerlandpresid trump tout describ blue...       pos

# 3. Modeling

## 3.1 Split training and test sets

In [143]:
# separate features and targets
X = processed_sentiment_corpus.iloc[:, 0]
y = processed_sentiment_corpus.iloc[:, 1]

# split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, stratify = y)
X_train, y_train = shuffle(X_train, y_train)

X_train.head(2)

12    hitth public struggl white hous advis kellyann...
32    presid trump end strong economi string domest ...
Name: text, dtype: object

In [144]:
le = LabelEncoder()
# get label name mapping
le.fit(y_train)
le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
print(le_name_mapping)

# encode the target 
y_train = le.fit_transform(y_train)
y_test = le.fit_transform(y_test)

{'neg': 0, 'neutral': 1, 'pos': 2}


## 3.2 Getting document term matrices

### 3.2.1 Create matrix of token counts using unigram, bigram and trigram tokens

In [145]:
# define a function to get unigram, bigram, and trigram matrix of token counts

def get_DTM(Ngram_range, x_train, x_test):
    vectorizer = CountVectorizer(stop_words='english', min_df = int(3), max_df = 0.5, 
                                 ngram_range = Ngram_range, binary=True) 
    vectorizer.fit(x_train)
    trans_x_train = vectorizer.transform(x_train)
    trans_x_test = vectorizer.transform(x_test)
    
    return trans_x_train, trans_x_test

In [146]:
# unigram token counts matrix
binary1_train, binary1_test = get_DTM(Ngram_range = (1, 1), x_train = X_train, x_test = X_test)

# bigram token counts matrix
binary2_train, binary2_test = get_DTM(Ngram_range = (1, 2), x_train = X_train, x_test = X_test)

# trigram token counts matrix
binary3_train, binary3_test = get_DTM(Ngram_range = (1, 3), x_train = X_train, x_test = X_test)

In [147]:
print("The unique terms in binary1_train is:", binary1_train.toarray().shape[1])
print("The unique terms in binary2_train is:", binary2_train.toarray().shape[1])
print("The unique terms in binary3_train is:", binary3_train.toarray().shape[1])

The unique terms in binary1_train is: 1137
The unique terms in binary2_train is: 1473
The unique terms in binary3_train is: 1568


### 3.2.2 Create DTM using unigram, bigram and trigram term frequency

In [148]:
# define a function to get unigram, bigram, and trigram term frequency matrix

def get_TF_DTM(Ngram_range, x_train, x_test):
    vectorizer = CountVectorizer(stop_words='english', min_df = int(3), max_df = 0.5, ngram_range = Ngram_range) 
    vectorizer.fit(x_train)
    trans_x_train = vectorizer.transform(x_train)
    trans_x_test = vectorizer.transform(x_test)
    
    return trans_x_train, trans_x_test

In [149]:
# unigram tf matrix
tf1_train, tf1_test = get_TF_DTM(Ngram_range = (1, 1), x_train = X_train, x_test = X_test)

# bigram tf matrix
tf2_train, tf2_test = get_TF_DTM(Ngram_range = (1, 2), x_train = X_train, x_test = X_test)

# trigram tf matrix
tf3_train, tf3_test = get_TF_DTM(Ngram_range = (1, 3), x_train = X_train, x_test = X_test)

In [150]:
print("The unique terms in tf1_train is:", tf1_train.toarray().shape[1])
print("The unique terms in tf2_train is:", tf2_train.toarray().shape[1])
print("The unique terms in tf3_train is:", tf3_train.toarray().shape[1])

The unique terms in tf1_train is: 1137
The unique terms in tf2_train is: 1473
The unique terms in tf3_train is: 1568


### 3.2.3 Create DTM using unigram, bigram and trigram TF-IDF

In [151]:
# define a function to get unigram, bigram, and trigram TF-IDF matrix

def get_TF_IDF_DTM(Ngram_range, x_train, x_test):
    vectorizer = TfidfVectorizer(stop_words='english', min_df = int(3), max_df = 0.5, 
                                 ngram_range = Ngram_range) 
    vectorizer.fit(x_train)
    trans_x_train = vectorizer.transform(x_train)
    trans_x_test = vectorizer.transform(x_test)
    
    return trans_x_train, trans_x_test

In [152]:

# unigram tf-idf matrix
tfidf1_train, tfidf1_test = get_TF_IDF_DTM(Ngram_range = (1, 1), x_train = X_train, x_test = X_test)

# bigram tf-idf matrix
tfidf2_train, tfidf2_test = get_TF_IDF_DTM(Ngram_range = (1, 2), x_train = X_train, x_test = X_test)

# trigram tf-idf matrix
tfidf3_train, tfidf3_test = get_TF_IDF_DTM(Ngram_range = (1, 3), x_train = X_train, x_test = X_test)

In [153]:
print("The unique terms in tfidf1_train is:", tfidf1_train.toarray().shape[1])
print("The unique terms in tfidf2_train is:", tfidf2_train.toarray().shape[1])
print("The unique terms in tfidf3_train is:", tfidf3_train.toarray().shape[1])

The unique terms in tfidf1_train is: 1137
The unique terms in tfidf2_train is: 1473
The unique terms in tfidf3_train is: 1568


## 3.3 Modeling

### 3.3.1 XGBoost Classifier

In [154]:
# define model training
def train_model(clf, dtm, test):
    # train data
    clf.fit(dtm, y_train)
    
    # Predicting on the test set
    preds = clf.predict(test)
    
    # print evaluation matrix
    print("Accuracy:", '{:1.4f}'.format(accuracy_score(y_test, preds)))
    print("")
    print(classification_report(y_test, preds))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, preds))
    
    return '{:1.4f}'.format(accuracy_score(y_test, preds))

In [155]:
# Use Naive Bayes
clf = XGBClassifier() #MultinomialNB()
clf = svm.SVC(gamma = 'scale', C = 1.0)
#param = {'max_depth': 3, 'eta': 0.3, 'objective':'multi:softmax', 'num_class': 3}
# param = {'max_depth': 3, 'learning_rate ': 0.3, 'objective':'multi:softmax'}
#xgb_clf = XGBClassifier(param)
#xgb_clf = XGBClassifier(max_depth=3, learning_rate=0.3, objective='multi:softmax')
xgb_clf = XGBClassifier(max_depth=3, learning_rate=0.3, objective='multi:softmax', num_class=3)
svm_clf = svm.SVC(gamma = 'scale', C = 1.0)
# reference: https://medium.com/@gabrielziegler3/multiclass-multilabel-classification-with-xgboost-66195e4d9f2d
# reference: https://xgboost.readthedocs.io/en/latest/parameter.html

# Model Configurations
binary1 = ("unigram, binary", binary1_train, binary1_test)
binary2 = ("bigram, binary",  binary2_train, binary2_test)
binary3 = ("trigram, binary", binary3_train, binary3_test)
tf1 = ("unigram, TF", tf1_train, tf1_test)
tf2 = ("bigram, TF",  tf2_train, tf2_test)
tf3 = ("trigram, TF", tf3_train, tf3_test)
tfidf1 = ("unigram, TF-IDF", tfidf1_train, tfidf1_test)
tfidf2 = ("bigram, TF-IDF",  tfidf2_train, tfidf2_test)
tfidf3 = ("trigram, TF-IDF", tfidf3_train, tfidf3_test)
DTMs = [binary1, binary2, binary3,
        tf1, tf2, tf3,
        tfidf1, tfidf2, tfidf3]

df = pd.DataFrame({"config": [],
                   "accuracy": []})
best_config = ["Best Configuration", "none", 0, "none", "none"]
for data in DTMs:
    print(data[0])
    print("")
    score = train_model(clf = xgb_clf, dtm = data[1], test = data[2])
    print("======================================================")
    print("")
    if float(score) > float(best_config[2]):
        best_config = ["Best Configuration:", data[0], score, data[1], data[2]]
    df = df.append({"config": data[0],
               "accuracy": float(score)},
               ignore_index=True)

unigram, binary

Accuracy: 0.8750

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       1.00      1.00      1.00         3
           2       0.67      1.00      0.80         2

    accuracy                           0.88         8
   macro avg       0.89      0.89      0.87         8
weighted avg       0.92      0.88      0.88         8

Confusion Matrix:
[[2 0 1]
 [0 3 0]
 [0 0 2]]

bigram, binary

Accuracy: 0.8750

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         3
           1       1.00      1.00      1.00         3
           2       0.67      1.00      0.80         2

    accuracy                           0.88         8
   macro avg       0.89      0.89      0.87         8
weighted avg       0.92      0.88      0.88         8

Confusion Matrix:
[[2 0 1]
 [0 3 0]
 [0 0 2]]

trigram, binary

Accuracy: 0.7500

              precision    recall  f1-sc

### 3.3.2 SVM Classifier

In [156]:
# svm classifier
df_svm = pd.DataFrame({"config": [],
                   "accuracy": []})
best_config_svm = ["Best Configuration", "none", 0, "none", "none"]
for data in DTMs:
    print(data[0])
    print("")
    score = train_model(clf = svm_clf, dtm = data[1], test = data[2])
    print("======================================================")
    print("")
    if float(score) > float(best_config_svm[2]):
        best_config_svm = ["Best Configuration:", data[0], score, data[1], data[2]]
    df_svm = df_svm.append({"config": data[0],
               "accuracy": float(score)},
               ignore_index=True)

unigram, binary

Accuracy: 0.5000

              precision    recall  f1-score   support

           0       1.00      0.33      0.50         3
           1       0.43      1.00      0.60         3
           2       0.00      0.00      0.00         2

    accuracy                           0.50         8
   macro avg       0.48      0.44      0.37         8
weighted avg       0.54      0.50      0.41         8

Confusion Matrix:
[[1 2 0]
 [0 3 0]
 [0 2 0]]

bigram, binary

Accuracy: 0.5000

              precision    recall  f1-score   support

           0       1.00      0.33      0.50         3
           1       0.43      1.00      0.60         3
           2       0.00      0.00      0.00         2

    accuracy                           0.50         8
   macro avg       0.48      0.44      0.37         8
weighted avg       0.54      0.50      0.41         8

Confusion Matrix:
[[1 2 0]
 [0 3 0]
 [0 2 0]]

trigram, binary

Accuracy: 0.5000

              precision    recall  f1-sc

/Users/sa/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sa/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sa/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/sa/opt/anaconda3/lib/

In [157]:
# results of svm classifier
df_svm

config  accuracy
0  unigram, binary     0.500
1   bigram, binary     0.500
2  trigram, binary     0.500
3      unigram, TF     0.375
4       bigram, TF     0.375
5      trigram, TF     0.500
6  unigram, TF-IDF     0.500
7   bigram, TF-IDF     0.500
8  trigram, TF-IDF     0.500

In [158]:
# best model
print(best_config_svm)

['Best Configuration:', 'unigram, binary', '0.5000', <30x1137 sparse matrix of type '<class 'numpy.int64'>'
	with 6659 stored elements in Compressed Sparse Row format>, <8x1137 sparse matrix of type '<class 'numpy.int64'>'
	with 1624 stored elements in Compressed Sparse Row format>]


## 3.3.3 Random Forest Classifier

In [159]:
labels = processed_sentiment_corpus.sentiment
vectorizer = TfidfVectorizer (max_features=2500, min_df=7, max_df=0.8, stop_words=more_stop_words)
processed_features = vectorizer.fit_transform(processed_sentiment_corpus.text).toarray()
processed_features

/Users/sa/opt/anaconda3/lib/python3.7/site-packages/sklearn/feature_extraction/text.py:385: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['120', '40', 'accuracy', 'agreement', 'allcopyright', 'availability', 'available', 'byassociated', 'click', 'company', 'completeness', 'disclaim', 'disclaimerneither', 'electronic', 'express', 'fitness', 'fromtotranslatetranslationprogress', 'implied', 'infringment', 'lessyou', 'license', 'limitation', 'loadinganimation', 'merchantability', 'ms', 'neither', 'non', 'particular', 'photographs', 'post', 'press', 'products', 'purpose', 'rather', 'show', 'specifically', 'systemsproquest', 'timeliness', 'times', 'translatetranslation', 'trump', 'turn', 'undo', 'washinton', 'without', 'word'] not in stop_words.
  'stop_words.' % sorted(inconsistent))


array([[0.        , 0.        , 0.        , ..., 0.0505522 , 0.        ,
        0.        ],
       [0.        , 0.        , 0.0564099 , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.07222846, 0.        , ..., 0.        , 0.        ,
        0.0752669 ],
       ...,
       [0.09953687, 0.        , 0.04658299, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.02298697],
       [0.03228227, 0.03740242, 0.03021604, ..., 0.        , 0.03897583,
        0.        ]])

In [160]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(processed_features, labels, test_size=0.2, random_state=0)


text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)
text_classifier.fit(X_train1, y_train1)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [161]:
predictions = text_classifier.predict(X_test1)
print(confusion_matrix(y_test1,predictions))
print(classification_report(y_test1,predictions))
print("Random Forest Classifier Accuracy Score: " + str(accuracy_score(y_test1, predictions)))

[[2 4]
 [0 2]]
              precision    recall  f1-score   support

         neg       1.00      0.33      0.50         6
     neutral       0.33      1.00      0.50         2

    accuracy                           0.50         8
   macro avg       0.67      0.67      0.50         8
weighted avg       0.83      0.50      0.50         8

Random Forest Classifier Accuracy Score: 0.5
